- // MIR for `opt1` before InstSimplify
+ // MIR for `opt1` after InstSimplify
  
  fn opt1(_1: bool) -> u32 {
      debug x => _1;                       // in scope 0 at $DIR/outlining.rs:+0:9: +0:10
      let mut _0: u32;                     // return place in scope 0 at $DIR/outlining.rs:+0:21: +0:24
      let mut _2: bool;                    // in scope 0 at $DIR/outlining.rs:+1:8: +1:17
      let mut _3: bool;                    // in scope 0 at $DIR/outlining.rs:+1:8: +1:9
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/outlining.rs:+1:8: +1:17
          StorageLive(_3);                 // scope 0 at $DIR/outlining.rs:+1:8: +1:9
          _3 = _1;                         // scope 0 at $DIR/outlining.rs:+1:8: +1:9
-         _2 = Ne(move _3, const true);    // scope 0 at $DIR/outlining.rs:+1:8: +1:17
+         _2 = Not(move _3);               // scope 0 at $DIR/outlining.rs:+1:8: +1:17
          StorageDead(_3);                 // scope 0 at $DIR/outlining.rs:+1:16: +1:17
          switchInt(move _2) -> [0: bb2, otherwise: bb1]; // scope 0 at $DIR/outlining.rs:+1:8: +1:17
      }
  
      bb1: {
          _0 = const 0_u32;                // scope 0 at $DIR/outlining.rs:+2:9: +2:10
          goto -> bb3;                     // scope 0 at $DIR/outlining.rs:+1:5: +5:6
      }
  
      bb2: {
          _0 = const 1_u32;                // scope 0 at $DIR/outlining.rs:+4:9: +4:10
          goto -> bb3;                     // scope 0 at $DIR/outlining.rs:+1:5: +5:6
      }
  
      bb3: {
          StorageDead(_2);                 // scope 0 at $DIR/outlining.rs:+5:5: +5:6
          return;                          // scope 0 at $DIR/outlining.rs:+6:2: +6:2
      }
  }
  
